services:
  app:
    build: .
    container_name: powerguns-app
    expose:
      - "3000"
    environment:
      - DATABASE_URL=mysql://root:powerguns@mysql:3306/powerguns
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
